### ISSUE TITLE
Upload Problems 

### ISSUE THREAD

**Issue by petzlux** [opendatalu/gouvlu#94]
@noirbizarre 

The good news first: The upload fails due to spaces in the filename are resolved. this now works in our demoprod env with udata 1.5.3

The (kinda) bad news: we still have upload fails when trying to upload a 1gb file with the client UI showing red error messages and the following errors in the log. Weirdly, if I refresh the page, the Resource is displayed, and the SHA1 Hash matches the source file! So it seems to work afterall!? 

```
[2018-09-11 14:37:12,532] ERROR in app: Exception on /api/1/datasets/5ab8ebf7813ad311d9d17c93/upload/ [POST]
Traceback (most recent call last):
  File "/srv/udata/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/udata/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/udata/local/lib/python2.7/site-packages/flask_restplus/cors.py", line 38, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/srv/udata/local/lib/python2.7/site-packages/udata/api/__init__.py", line 123, in wrapper
    return func(*args, **kwargs)
  File "/srv/udata/local/lib/python2.7/site-packages/flask_restplus/api.py", line 319, in wrapper
    resp = resource(*args, **kwargs)
  File "/srv/udata/local/lib/python2.7/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/srv/udata/local/lib/python2.7/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/srv/udata/local/lib/python2.7/site-packages/udata/api/__init__.py", line 114, in wrapper
    return func(*args, **kwargs)
  File "/srv/udata/local/lib/python2.7/site-packages/flask_restplus/marshalling.py", line 136, in wrapper
    resp = f(*args, **kwargs)
  File "/srv/udata/local/lib/python2.7/site-packages/udata/core/dataset/api.py", line 258, in post
    infos = self.handle_upload(dataset)
  File "/srv/udata/local/lib/python2.7/site-packages/udata/core/dataset/api.py", line 239, in handle_upload
    infos = handle_upload(storages.resources, prefix)
  File "/srv/udata/local/lib/python2.7/site-packages/udata/core/storages/api.py", line 139, in handle_upload
    filename = combine_chunks(storage, args, prefix=prefix)
  File "/srv/udata/local/lib/python2.7/site-packages/udata/core/storages/api.py", line 124, in combine_chunks
    out.write(chunks.read(partname))
  File "/srv/udata/local/lib/python2.7/site-packages/flask_fs/storage.py", line 228, in read
    raise FileNotFound(filename)
FileNotFound: d87f5da8-3b4b-4e16-9448-52edd36faa38/0
Tue Sep 11 14:37:12 2018 - ...The work of process 14525 is done. Seeya!
Tue Sep 11 14:37:13 2018 - worker 4 killed successfully (pid: 14525)
Tue Sep 11 14:37:13 2018 - Respawned uWSGI worker 4 (new pid: 14535)
Tue Sep 11 14:37:13 2018 - mapping worker 4 to CPUs: 1
Tue Sep 11 14:37:17 2018 - WSGI app 0 (mountpoint='') ready in 4 seconds on interpreter 0x55cee87f8a20 pid: 14535 (default app)
[2018-09-11 14:37:23,433] ERROR in app: Exception on /api/1/datasets/5ab8ebf7813ad311d9d17c93/upload/ [POST]
Traceback (most recent call last):
  File "/srv/udata/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/udata/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/udata/local/lib/python2.7/site-packages/flask_restplus/cors.py", line 38, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/srv/udata/local/lib/python2.7/site-packages/udata/api/__init__.py", line 123, in wrapper
    return func(*args, **kwargs)
  File "/srv/udata/local/lib/python2.7/site-packages/flask_restplus/api.py", line 319, in wrapper
    resp = resource(*args, **kwargs)
  File "/srv/udata/local/lib/python2.7/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/srv/udata/local/lib/python2.7/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/srv/udata/local/lib/python2.7/site-packages/udata/api/__init__.py", line 114, in wrapper
    return func(*args, **kwargs)
  File "/srv/udata/local/lib/python2.7/site-packages/flask_restplus/marshalling.py", line 136, in wrapper
    resp = f(*args, **kwargs)
  File "/srv/udata/local/lib/python2.7/site-packages/udata/core/dataset/api.py", line 258, in post
    infos = self.handle_upload(dataset)
  File "/srv/udata/local/lib/python2.7/site-packages/udata/core/dataset/api.py", line 239, in handle_upload
    infos = handle_upload(storages.resources, prefix)
  File "/srv/udata/local/lib/python2.7/site-packages/udata/core/storages/api.py", line 139, in handle_upload
    filename = combine_chunks(storage, args, prefix=prefix)
  File "/srv/udata/local/lib/python2.7/site-packages/udata/core/storages/api.py", line 124, in combine_chunks
    out.write(chunks.read(partname))
  File "/srv/udata/local/lib/python2.7/site-packages/flask_fs/storage.py", line 228, in read
    raise FileNotFound(filename)
FileNotFound: d87f5da8-3b4b-4e16-9448-52edd36faa38/0
Tue Sep 11 14:37:23 2018 - ...The work of process 14535 is done. Seeya!
Tue Sep 11 14:37:24 2018 - worker 4 killed successfully (pid: 14535)
Tue Sep 11 14:37:24 2018 - Respawned uWSGI worker 4 (new pid: 14542)
Tue Sep 11 14:37:24 2018 - mapping worker 4 to CPUs: 1
```

**Comment by petzlux** [comment]
PS: Also check out the connected sentry errors:
https://sentry.data.public.lu/sentry/demoprod/issues/7808/

**Comment by jaykayone** [comment]
there is still an issue with the newest release when I try to upload 1GB file.

**Comment by jaykayone** [comment]
the file is uploaded and available as a ressource, but while uploading we get a 504 error

here is what we find in the logs

**Comment by rg444** [comment]
```
[2018-10-23 11:25:20,835] ERROR in app: Exception on /api/1/datasets/5bcee79bd782b021dc1b2929/upload/ [POST]
Traceback (most recent call last):
  File "/srv/udata/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/udata/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/udata/local/lib/python2.7/site-packages/flask_restplus/cors.py", line 38, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/srv/udata/local/lib/python2.7/site-packages/udata/api/__init__.py", line 123, in wrapper
    return func(*args, **kwargs)
  File "/srv/udata/local/lib/python2.7/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/srv/udata/local/lib/python2.7/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/srv/udata/local/lib/python2.7/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/srv/udata/local/lib/python2.7/site-packages/udata/api/__init__.py", line 114, in wrapper
    return func(*args, **kwargs)
  File "/srv/udata/local/lib/python2.7/site-packages/flask_restplus/marshalling.py", line 136, in wrapper
    resp = f(*args, **kwargs)
  File "/srv/udata/local/lib/python2.7/site-packages/udata/core/dataset/api.py", line 260, in post
    infos = self.handle_upload(dataset)
  File "/srv/udata/local/lib/python2.7/site-packages/udata/core/dataset/api.py", line 240, in handle_upload
    infos = handle_upload(storages.resources, prefix)
  File "/srv/udata/local/lib/python2.7/site-packages/udata/core/storages/api.py", line 139, in handle_upload
    filename = combine_chunks(storage, args, prefix=prefix)
  File "/srv/udata/local/lib/python2.7/site-packages/udata/core/storages/api.py", line 124, in combine_chunks
    out.write(chunks.read(partname))
  File "/srv/udata/local/lib/python2.7/site-packages/flask_fs/storage.py", line 228, in read
    raise FileNotFound(filename)
FileNotFound: 0c79bfae-238f-4d84-8d83-b2934e3230b0/0
Tue Oct 23 11:25:20 2018 - ...The work of process 9456 is done. Seeya!
Tue Oct 23 11:25:21 2018 - worker 4 killed successfully (pid: 9456)
Tue Oct 23 11:25:21 2018 - Respawned uWSGI worker 4 (new pid: 9470)
Tue Oct 23 11:25:21 2018 - mapping worker 4 to CPUs: 1
Tue Oct 23 11:25:25 2018 - WSGI app 0 (mountpoint='') ready in 4 seconds on interpreter 0x5594b73b4a20 pid: 9470 (default app)
[2018-10-23 11:25:32,081] ERROR in app: Exception on /api/1/datasets/5bcee79bd782b021dc1b2929/upload/ [POST]
Traceback (most recent call last):
  File "/srv/udata/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/udata/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/udata/local/lib/python2.7/site-packages/flask_restplus/cors.py", line 38, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/srv/udata/local/lib/python2.7/site-packages/udata/api/__init__.py", line 123, in wrapper
    return func(*args, **kwargs)
  File "/srv/udata/local/lib/python2.7/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/srv/udata/local/lib/python2.7/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/srv/udata/local/lib/python2.7/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/srv/udata/local/lib/python2.7/site-packages/udata/api/__init__.py", line 114, in wrapper
    return func(*args, **kwargs)
  File "/srv/udata/local/lib/python2.7/site-packages/flask_restplus/marshalling.py", line 136, in wrapper
    resp = f(*args, **kwargs)
  File "/srv/udata/local/lib/python2.7/site-packages/udata/core/dataset/api.py", line 260, in post
    infos = self.handle_upload(dataset)
  File "/srv/udata/local/lib/python2.7/site-packages/udata/core/dataset/api.py", line 240, in handle_upload
    infos = handle_upload(storages.resources, prefix)
  File "/srv/udata/local/lib/python2.7/site-packages/udata/core/storages/api.py", line 139, in handle_upload
    filename = combine_chunks(storage, args, prefix=prefix)
  File "/srv/udata/local/lib/python2.7/site-packages/udata/core/storages/api.py", line 124, in combine_chunks
    out.write(chunks.read(partname))
  File "/srv/udata/local/lib/python2.7/site-packages/flask_fs/storage.py", line 228, in read
    raise FileNotFound(filename)
FileNotFound: 0c79bfae-238f-4d84-8d83-b2934e3230b0/0
```

**Comment by jaykayone** [comment]
here is the dataset: https://demoprod.data.public.lu/fr/admin/dataset/5bcee79bd782b021dc1b2929

**Comment by jaykayone** [comment]
https://demoprod.data.public.lu/fr/datasets/test-upload-big-data/

**Comment by jaykayone** [comment]
we will try using sticky sessions and monitor where the 504 comes frmo

**Comment by jaykayone** [comment]
even when using sticky sessions, we still get the filenotfound error:

```
Mon Oct 29 09:20:40 2018 - ...The work of process 29221 is done. Seeya!
[2018-10-29 09:20:41,119] ERROR in app: Exception on /api/1/datasets/5bcee79bd782b021dc1b2929/upload/ [POST]
Traceback (most recent call last):
  File "/srv/udata/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/udata/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/udata/local/lib/python2.7/site-packages/flask_restplus/cors.py", line 38, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/srv/udata/local/lib/python2.7/site-packages/udata/api/__init__.py", line 123, in wrapper
    return func(*args, **kwargs)
  File "/srv/udata/local/lib/python2.7/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/srv/udata/local/lib/python2.7/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/srv/udata/local/lib/python2.7/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/srv/udata/local/lib/python2.7/site-packages/udata/api/__init__.py", line 114, in wrapper
    return func(*args, **kwargs)
  File "/srv/udata/local/lib/python2.7/site-packages/flask_restplus/marshalling.py", line 136, in wrapper
    resp = f(*args, **kwargs)
  File "/srv/udata/local/lib/python2.7/site-packages/udata/core/dataset/api.py", line 260, in post
    infos = self.handle_upload(dataset)
  File "/srv/udata/local/lib/python2.7/site-packages/udata/core/dataset/api.py", line 240, in handle_upload
    infos = handle_upload(storages.resources, prefix)
  File "/srv/udata/local/lib/python2.7/site-packages/udata/core/storages/api.py", line 139, in handle_upload
    filename = combine_chunks(storage, args, prefix=prefix)
  File "/srv/udata/local/lib/python2.7/site-packages/udata/core/storages/api.py", line 124, in combine_chunks
    out.write(chunks.read(partname))
  File "/srv/udata/local/lib/python2.7/site-packages/flask_fs/storage.py", line 228, in read
    raise FileNotFound(filename)
FileNotFound: a833d53d-9be4-49d0-bfc0-d444c91e486e/0
Mon Oct 29 09:20:41 2018 - ...The work of process 29217 is done. Seeya!
Mon Oct 29 09:20:42 2018 - worker 2 killed successfully (pid: 29217)
Mon Oct 29 09:20:42 2018 - Respawned uWSGI worker 2 (new pid: 29251)
Mon Oct 29 09:20:42 2018 - worker 4 killed successfully (pid: 29221)
Mon Oct 29 09:20:42 2018 - Respawned uWSGI worker 4 (new pid: 29252)
Mon Oct 29 09:20:42 2018 - mapping worker 2 to CPUs: 1
Mon Oct 29 09:20:42 2018 - mapping worker 4 to CPUs: 1
[2018-10-29 09:20:46,723] ERROR in app: Exception on /api/1/datasets/5bcee79bd782b021dc1b2929/upload/ [POST]
Traceback (most recent call last):
  File "/srv/udata/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/udata/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/udata/local/lib/python2.7/site-packages/flask_restplus/cors.py", line 38, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/srv/udata/local/lib/python2.7/site-packages/udata/api/__init__.py", line 123, in wrapper
    return func(*args, **kwargs)
  File "/srv/udata/local/lib/python2.7/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/srv/udata/local/lib/python2.7/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/srv/udata/local/lib/python2.7/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/srv/udata/local/lib/python2.7/site-packages/udata/api/__init__.py", line 114, in wrapper
    return func(*args, **kwargs)
  File "/srv/udata/local/lib/python2.7/site-packages/flask_restplus/marshalling.py", line 136, in wrapper
    resp = f(*args, **kwargs)
  File "/srv/udata/local/lib/python2.7/site-packages/udata/core/dataset/api.py", line 260, in post
    infos = self.handle_upload(dataset)
  File "/srv/udata/local/lib/python2.7/site-packages/udata/core/dataset/api.py", line 240, in handle_upload
    infos = handle_upload(storages.resources, prefix)
  File "/srv/udata/local/lib/python2.7/site-packages/udata/core/storages/api.py", line 139, in handle_upload
    filename = combine_chunks(storage, args, prefix=prefix)
  File "/srv/udata/local/lib/python2.7/site-packages/udata/core/storages/api.py", line 124, in combine_chunks
    out.write(chunks.read(partname))
  File "/srv/udata/local/lib/python2.7/site-packages/flask_fs/storage.py", line 228, in read
    raise FileNotFound(filename)
FileNotFound: a833d53d-9be4-49d0-bfc0-d444c91e486e/0
Mon Oct 29 09:20:46 2018 - ...The work of process 29242 is done. Seeya!
Mon Oct 29 09:20:47 2018 - worker 1 killed successfully (pid: 29242)
Mon Oct 29 09:20:47 2018 - Respawned uWSGI worker 1 (new pid: 29263)
Mon Oct 29 09:20:47 2018 - mapping worker 1 to CPUs: 0
Mon Oct 29 09:20:49 2018 - WSGI app 0 (mountpoint='') ready in 7 seconds on interpreter 0x5594b73b4a20 pid: 29251 (default app)
Mon Oct 29 09:20:49 2018 - WSGI app 0 (mountpoint='') ready in 7 seconds on interpreter 0x5594b73b4a20 pid: 29252 (default app)
Mon Oct 29 09:20:51 2018 - WSGI app 0 (mountpoint='') ready in 4 seconds on interpreter 0x5594b73b4a20 pid: 29263 (default app)
[2018-10-29 09:20:54,742] ERROR in app: Exception on /api/1/datasets/5bcee79bd782b021dc1b2929/upload/ [POST]
Traceback (most recent call last):
  File "/srv/udata/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/udata/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/udata/local/lib/python2.7/site-packages/flask_restplus/cors.py", line 38, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/srv/udata/local/lib/python2.7/site-packages/udata/api/__init__.py", line 123, in wrapper
    return func(*args, **kwargs)
  File "/srv/udata/local/lib/python2.7/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/srv/udata/local/lib/python2.7/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/srv/udata/local/lib/python2.7/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/srv/udata/local/lib/python2.7/site-packages/udata/api/__init__.py", line 114, in wrapper
    return func(*args, **kwargs)
  File "/srv/udata/local/lib/python2.7/site-packages/flask_restplus/marshalling.py", line 136, in wrapper
    resp = f(*args, **kwargs)
  File "/srv/udata/local/lib/python2.7/site-packages/udata/core/dataset/api.py", line 260, in post
    infos = self.handle_upload(dataset)
  File "/srv/udata/local/lib/python2.7/site-packages/udata/core/dataset/api.py", line 240, in handle_upload
    infos = handle_upload(storages.resources, prefix)
  File "/srv/udata/local/lib/python2.7/site-packages/udata/core/storages/api.py", line 139, in handle_upload
    filename = combine_chunks(storage, args, prefix=prefix)
  File "/srv/udata/local/lib/python2.7/site-packages/udata/core/storages/api.py", line 124, in combine_chunks
    out.write(chunks.read(partname))
  File "/srv/udata/local/lib/python2.7/site-packages/flask_fs/storage.py", line 228, in read
    raise FileNotFound(filename)
FileNotFound: a833d53d-9be4-49d0-bfc0-d444c91e486e/0
Mon Oct 29 09:21:10 2018 - ...The work of process 29252 is done. Seeya!
Mon Oct 29 09:21:11 2018 - worker 4 killed successfully (pid: 29252)
Mon Oct 29 09:21:11 2018 - Respawned uWSGI worker 4 (new pid: 29276)
Mon Oct 29 09:21:11 2018 - mapping worker 4 to CPUs: 1
Mon Oct 29 09:21:15 2018 - WSGI app 0 (mountpoint='') ready in 4 seconds on interpreter 0x5594b73b4a20 pid: 29276 (default app)
Mon Oct 29 09:21:40 2018 - ...The work of process 29263 is done. Seeya!
Mon Oct 29 09:21:41 2018 - worker 1 killed successfully (pid: 29263)
Mon Oct 29 09:21:41 2018 - Respawned uWSGI worker 1 (new pid: 29281)
Mon Oct 29 09:21:41 2018 - mapping worker 1 to CPUs: 0
Mon Oct 29 09:21:44 2018 - WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0x5594b73b4a20 pid: 29281 (default app)
Mon Oct 29 09:21:46 2018 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /api/1/datasets/5bcee79bd782b021dc1b2929/upload/ (ip 10.10.12.44) !!!
Mon Oct 29 09:21:46 2018 - uwsgi_response_writev_headers_and_body_do(): Broken pipe [core/writer.c line 296] during POST /api/1/datasets/5bcee79bd782b021dc1b2929/upload/ (10.10.12.44)
IOError: write error
Mon Oct 29 09:21:46 2018 - ...The work of process 29203 is done. Seeya!
Mon Oct 29 09:21:47 2018 - worker 5 killed successfully (pid: 29203)
Mon Oct 29 09:21:47 2018 - Respawned uWSGI worker 5 (new pid: 29287)
Mon Oct 29 09:21:47 2018 - mapping worker 5 to CPUs: 0
Mon Oct 29 09:21:50 2018 - WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0x5594b73b4a20 pid: 29287 (default app)
Mon Oct 29 09:22:10 2018 - ...The work of process 29276 is done. Seeya!
Mon Oct 29 09:22:11 2018 - worker 4 killed successfully (pid: 29276)
Mon Oct 29 09:22:11 2018 - Respawned uWSGI worker 4 (new pid: 29313)
Mon Oct 29 09:22:11 2018 - mapping worker 4 to CPUs: 1
Mon Oct 29 09:22:14 2018 - WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0x5594b73b4a20 pid: 29313 (default app)
Mon Oct 29 09:22:40 2018 - ...The work of process 29287 is done. Seeya!
Mon Oct 29 09:22:41 2018 - worker 5 killed successfully (pid: 29287)
Mon Oct 29 09:22:41 2018 - Respawned uWSGI worker 5 (new pid: 29319)
Mon Oct 29 09:22:41 2018 - mapping worker 5 to CPUs: 0
Mon Oct 29 09:22:44 2018 - WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0x5594b73b4a20 pid: 29319 (default app)
Mon Oct 29 09:23:10 2018 - ...The work of process 29313 is done. Seeya!
Mon Oct 29 09:23:11 2018 - worker 4 killed successfully (pid: 29313)
Mon Oct 29 09:23:11 2018 - Respawned uWSGI worker 4 (new pid: 29325)
Mon Oct 29 09:23:11 2018 - mapping worker 4 to CPUs: 1
Mon Oct 29 09:23:14 2018 - WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0x5594b73b4a20 pid: 29325 (default app)
Mon Oct 29 09:23:40 2018 - ...The work of process 29325 is done. Seeya!
Mon Oct 29 09:23:41 2018 - worker 4 killed successfully (pid: 29325)
Mon Oct 29 09:23:41 2018 - Respawned uWSGI worker 4 (new pid: 29346)
Mon Oct 29 09:23:41 2018 - mapping worker 4 to CPUs: 1
Mon Oct 29 09:23:44 2018 - WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0x5594b73b4a20 pid: 29346 (default app)
Mon Oct 29 09:24:06 2018 - ...The work of process 29319 is done. Seeya!
Mon Oct 29 09:24:07 2018 - worker 5 killed successfully (pid: 29319)
Mon Oct 29 09:24:07 2018 - Respawned uWSGI worker 5 (new pid: 29368)
Mon Oct 29 09:24:07 2018 - mapping worker 5 to CPUs: 0
Mon Oct 29 09:24:11 2018 - ...The work of process 29281 is done. Seeya!
Mon Oct 29 09:24:11 2018 - WSGI app 0 (mountpoint='') ready in 4 seconds on interpreter 0x5594b73b4a20 pid: 29368 (default app)
Mon Oct 29 09:24:12 2018 - worker 1 killed successfully (pid: 29281)
Mon Oct 29 09:24:12 2018 - Respawned uWSGI worker 1 (new pid: 29374)
Mon Oct 29 09:24:12 2018 - mapping worker 1 to CPUs: 0
Mon Oct 29 09:24:15 2018 - WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0x5594b73b4a20 pid: 29374 (default app)
Mon Oct 29 09:24:40 2018 - ...The work of process 29346 is done. Seeya!
Mon Oct 29 09:24:41 2018 - worker 4 killed successfully (pid: 29346)
Mon Oct 29 09:24:41 2018 - Respawned uWSGI worker 4 (new pid: 29380)
Mon Oct 29 09:24:41 2018 - mapping worker 4 to CPUs: 1
Mon Oct 29 09:24:44 2018 - WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0x5594b73b4a20 pid: 29380 (default app)
Mon Oct 29 09:25:10 2018 - ...The work of process 29374 is done. Seeya!
Mon Oct 29 09:25:11 2018 - worker 1 killed successfully (pid: 29374)
Mon Oct 29 09:25:11 2018 - Respawned uWSGI worker 1 (new pid: 29386)
Mon Oct 29 09:25:11 2018 - mapping worker 1 to CPUs: 0
Mon Oct 29 09:25:14 2018 - WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0x5594b73b4a20 pid: 29386 (default app)
Mon Oct 29 09:25:40 2018 - ...The work of process 29380 is done. Seeya!
Mon Oct 29 09:25:41 2018 - worker 4 killed successfully (pid: 29380)
Mon Oct 29 09:25:41 2018 - Respawned uWSGI worker 4 (new pid: 29392)
Mon Oct 29 09:25:41 2018 - mapping worker 4 to CPUs: 1
Mon Oct 29 09:25:44 2018 - WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0x5594b73b4a20 pid: 29392 (default app)
Mon Oct 29 09:26:10 2018 - ...The work of process 29386 is done. Seeya!
Mon Oct 29 09:26:11 2018 - worker 1 killed successfully (pid: 29386)
Mon Oct 29 09:26:11 2018 - Respawned uWSGI worker 1 (new pid: 29398)
Mon Oct 29 09:26:11 2018 - mapping worker 1 to CPUs: 0
Mon Oct 29 09:26:14 2018 - WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0x5594b73b4a20 pid: 29398 (default app)
Mon Oct 29 09:26:40 2018 - ...The work of process 29392 is done. Seeya!
Mon Oct 29 09:26:41 2018 - worker 4 killed successfully (pid: 29392)
Mon Oct 29 09:26:41 2018 - Respawned uWSGI worker 4 (new pid: 29404)
Mon Oct 29 09:26:41 2018 - mapping worker 4 to CPUs: 1
Mon Oct 29 09:26:44 2018 - WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0x5594b73b4a20 pid: 29404 (default app)
Mon Oct 29 09:27:10 2018 - ...The work of process 29398 is done. Seeya!
Mon Oct 29 09:27:11 2018 - worker 1 killed successfully (pid: 29398)
Mon Oct 29 09:27:11 2018 - Respawned uWSGI worker 1 (new pid: 29410)
Mon Oct 29 09:27:11 2018 - mapping worker 1 to CPUs: 0
Mon Oct 29 09:27:14 2018 - WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0x5594b73b4a20 pid: 29410 (default app)
Mon Oct 29 09:27:40 2018 - ...The work of process 29404 is done. Seeya!
Mon Oct 29 09:27:41 2018 - worker 4 killed successfully (pid: 29404)
Mon Oct 29 09:27:41 2018 - Respawned uWSGI worker 4 (new pid: 29416)
Mon Oct 29 09:27:41 2018 - mapping worker 4 to CPUs: 1
Mon Oct 29 09:27:44 2018 - WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0x5594b73b4a20 pid: 29416 (default app)
Mon Oct 29 09:28:10 2018 - ...The work of process 29416 is done. Seeya!
Mon Oct 29 09:28:11 2018 - worker 4 killed successfully (pid: 29416)
Mon Oct 29 09:28:11 2018 - Respawned uWSGI worker 4 (new pid: 29422)
Mon Oct 29 09:28:11 2018 - mapping worker 4 to CPUs: 1
Mon Oct 29 09:28:14 2018 - WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0x5594b73b4a20 pid: 29422 (default app)
Mon Oct 29 09:28:40 2018 - ...The work of process 29410 is done. Seeya!
Mon Oct 29 09:28:41 2018 - worker 1 killed successfully (pid: 29410)
Mon Oct 29 09:28:41 2018 - Respawned uWSGI worker 1 (new pid: 29428)
Mon Oct 29 09:28:41 2018 - mapping worker 1 to CPUs: 0
Mon Oct 29 09:28:44 2018 - WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0x5594b73b4a20 pid: 29428 (default app)
Mon Oct 29 09:29:10 2018 - ...The work of process 29422 is done. Seeya!
Mon Oct 29 09:29:11 2018 - worker 4 killed successfully (pid: 29422)
Mon Oct 29 09:29:11 2018 - Respawned uWSGI worker 4 (new pid: 29439)
Mon Oct 29 09:29:11 2018 - mapping worker 4 to CPUs: 1
Mon Oct 29 09:29:14 2018 - WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0x5594b73b4a20 pid: 29439 (default app)
Mon Oct 29 09:29:40 2018 - ...The work of process 29439 is done. Seeya!
Mon Oct 29 09:29:41 2018 - worker 4 killed successfully (pid: 29439)
Mon Oct 29 09:29:41 2018 - Respawned uWSGI worker 4 (new pid: 29445)
Mon Oct 29 09:29:41 2018 - mapping worker 4 to CPUs: 1
Mon Oct 29 09:29:44 2018 - WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0x5594b73b4a20 pid: 29445 (default app)
Mon Oct 29 09:30:10 2018 - ...The work of process 29428 is done. Seeya!
Mon Oct 29 09:30:11 2018 - worker 1 killed successfully (pid: 29428)
Mon Oct 29 09:30:11 2018 - Respawned uWSGI worker 1 (new pid: 29451)
Mon Oct 29 09:30:11 2018 - mapping worker 1 to CPUs: 0
Mon Oct 29 09:30:14 2018 - WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0x5594b73b4a20 pid: 29451 (default app)
Mon Oct 29 09:30:40 2018 - ...The work of process 29445 is done. Seeya!
Mon Oct 29 09:30:41 2018 - worker 4 killed successfully (pid: 29445)
Mon Oct 29 09:30:41 2018 - Respawned uWSGI worker 4 (new pid: 29457)
Mon Oct 29 09:30:41 2018 - mapping worker 4 to CPUs: 1
Mon Oct 29 09:30:44 2018 - WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0x5594b73b4a20 pid: 29457 (default app)
Mon Oct 29 09:31:10 2018 - ...The work of process 29451 is done. Seeya!
Mon Oct 29 09:31:11 2018 - worker 1 killed successfully (pid: 29451)
Mon Oct 29 09:31:11 2018 - Respawned uWSGI worker 1 (new pid: 29463)
Mon Oct 29 09:31:11 2018 - mapping worker 1 to CPUs: 0
Mon Oct 29 09:31:14 2018 - WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0x5594b73b4a20 pid: 29463 (default app)
Mon Oct 29 09:31:40 2018 - ...The work of process 29457 is done. Seeya!
Mon Oct 29 09:31:41 2018 - worker 4 killed successfully (pid: 29457)
Mon Oct 29 09:31:41 2018 - Respawned uWSGI worker 4 (new pid: 29479)
Mon Oct 29 09:31:41 2018 - mapping worker 4 to CPUs: 1
Mon Oct 29 09:31:44 2018 - WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0x5594b73b4a20 pid: 29479 (default app)
Mon Oct 29 09:32:10 2018 - ...The work of process 29463 is done. Seeya!
Mon Oct 29 09:32:11 2018 - worker 1 killed successfully (pid: 29463)
Mon Oct 29 09:32:11 2018 - Respawned uWSGI worker 1 (new pid: 29485)
Mon Oct 29 09:32:11 2018 - mapping worker 1 to CPUs: 0
```

**Comment by jaykayone** [comment]
OK, raising the idle timeout on the loadbalancer seems to have helped.
I will do some more test

**Comment by jaykayone** [comment]
I succesfully uploaded a  2GB file.
I had tried with 22Gb and 6.32GB, that did not work though

**Comment by petzlux** [comment]
Cloudfront ?

**Comment by jaykayone** [comment]
I think we can close this issue for now
